[pytest]
addopts = --alluredir=reports/allure-results --tb=short
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: marks tests as ui tests
    api: marks tests as api tests